List<String> regiones = [
  "Arica y Parinacota",
  "Tarapacá",
  "Antofagasta",
  "Atacama",
  "Coquimbo",
  "Valparaíso",
  "Metropolitana de Santiago",
  "Libertador Gral. Bernardo O’Higgins",
  "Maule",
  "Ñuble",
  "Biobío",
  "Araucanía",
  "Los Ríos",
  "Los Lagos",
  "Aisén",
  "Magallanes y de la Antártica Chilena",
];

Map comunas = {
  "Arica y Parinacota": [
    "Arica",
    "Camarones",
    "General Lagos",
    "Putre",
  ],
  "Tarapacá": [
    "Alto Hospicio",
    "Camiña",
    "Colchane",
    "Huara",
    "Iquique",
    "Pica",
    "Pozo Almonte"
  ],
  "Antofagasta": [
    "Antofagasta",
    "Calama",
    "María Elena",
    "Mejillones",
    "Ollagüe",
    "San Pedro de Atacama",
    "Sierra Gorda",
    "Taltal",
    "Tocopilla"
  ],
  "Atacama": [
    "Alto del Carmen",
    "Caldera",
    "Chañaral",
    "Copiapó",
    "Diego de Almagro",
    "Freirina",
    "Huasco",
    "Tierra Amarilla",
    "Vallenar"
  ],
  "Coquimbo": [
    "Andacollo",
    "Canela",
    "Combarbalá",
    "Coquimbo",
    "Illapel",
    "La Higuera",
    "La Serena",
    "Los Vilos",
    "Monte Patria",
    "Ovalle",
    "Paiguano",
    "Punitaqui",
    "Río Hurtado",
    "Salamanca",
    "Vicuña"
  ],
  "Valparaíso": [
    "Algarrobo",
    "Cabildo",
    "Calera",
    "Calle Larga",
    "Cartagena",
    "Casablanca",
    "Catemu",
    "Concón",
    "El Quisco",
    "El Tabo",
    "Hijuelas",
    "Isla de Pascua",
    "Juan Fernández",
    "La Cruz",
    "La Ligua",
    "Limache",
    "Llaillay",
    "Los Andes",
    "Nogales",
    "Olmué",
    "Panquehue",
    "Papudo",
    "Petorca",
    "Puchuncaví",
    "Putaendo",
    "Quillota",
    "Quilpué",
    "Quintero",
    "Rinconada",
    "San Antonio",
    "San Esteban",
    "San Felipe",
    "Santa María",
    "Santo Domingo",
    "Valparaíso",
    "Villa Alemana",
    "Viña del Mar",
    "Zapallar"
  ],
  "Metropolitana de Santiago": [
    "Alhué",
    "Buin",
    "Calera de Tango",
    "Cerrillos",
    "Cerro Navia",
    "Colina",
    "Conchalí",
    "Curacaví",
    "El Bosque",
    "El Monte",
    "Estación Central",
    "Huechuraba",
    "Independencia",
    "Isla de Maipo",
    "La Cisterna",
    "La Florida",
    "La Granja",
    "La Pintana",
    "La Reina",
    "Lampa",
    "Las Condes",
    "Lo Barnechea",
    "Lo Espejo",
    "Lo Prado",
    "Macul",
    "Maipú",
    "María Pinto",
    "Melipilla",
    "Ñuñoa",
    "Padre Hurtado",
    "Paine",
    "Pedro Aguirre Cerda",
    "Peñaflor",
    "Peñalolén",
    "Pirque",
    "Providencia",
    "Pudahuel",
    "Puente Alto",
    "Quilicura",
    "Quinta Normal",
    "Recoleta",
    "Renca",
    "San Bernardo",
    "San Joaquín",
    "San José de Maipo",
    "San Miguel",
    "San Pedro",
    "San Ramón",
    "Santiago",
    "Talagante",
    "Tiltil",
    "Vitacura"
  ],
  "Libertador Gral. Bernardo O’Higgins": [
    "Chimbarongo",
    "Chépica",
    "Codegua",
    "Coinco",
    "Coltauco",
    "Doñihue",
    "Graneros",
    "La Estrella",
    "Las Cabras",
    "Litueche",
    "Lolol",
    "Machalí",
    "Malloa",
    "Marchihue",
    "Nancagua",
    "Navidad",
    "Olivar",
    "Palmilla",
    "Paredones",
    "Peralillo",
    "Peumo",
    "Pichidegua",
    "Pichilemu",
    "Placilla",
    "Pumanque",
    "Quinta de Tilcoco",
    "Rancagua",
    "Rengo",
    "Requínoa",
    "San Fernando",
    "San Francisco de Mostazal",
    "San Vicente de Tagua Tagua",
    "Santa Cruz"
  ],
  "Maule": [
    "Cauquenes",
    "Chanco",
    "Colbún",
    "Constitución",
    "Curepto",
    "Curicó",
    "Empedrado",
    "Hualañé",
    "Licantén",
    "Linares",
    "Longaví",
    "Maule",
    "Molina",
    "Parral",
    "Pelarco",
    "Pelluhue",
    "Pencahue",
    "Rauco",
    "Retiro",
    "Romeral",
    "Río Claro",
    "Sagrada Familia",
    "San Clemente",
    "San Javier de Loncomilla",
    "San Rafael",
    "Talca",
    "Teno",
    "Vichuquén",
    "Villa Alegre",
    "Yerbas Buenas"
  ],
  "Ñuble": [
    "Bulnes",
    "Chillán Viejo",
    "Chillán",
    "Cobquecura",
    "Coelemu",
    "Coihueco",
    "El Carmen",
    "Ninhue",
    "Ñiquén",
    "Pemuco",
    "Pinto",
    "Portezuelo",
    "Quillón",
    "Quirihue",
    "Ránquil",
    "San Carlos",
    "San Fabián",
    "San Ignacio",
    "San Nicolás",
    "Treguaco",
    "Yungay"
  ],
  "Biobío": [
    "Alto Biobío",
    "Antuco",
    "Arauco",
    "Cabrero",
    "Cañete",
    "Chiguayante",
    "Concepción",
    "Contulmo",
    "Coronel",
    "Curanilahue",
    "Florida",
    "Hualpén",
    "Hualqui",
    "Laja",
    "Lebu",
    "Los Álamos",
    "Los Ángeles",
    "Lota",
    "Mulchén",
    "Nacimiento",
    "Negrete",
    "Penco",
    "Quilaco",
    "Quilleco",
    "San Pedro de la Paz",
    "San Rosendo",
    "Santa Bárbara",
    "Santa Juana",
    "Talcahuano",
    "Tirúa",
    "Tomé",
    "Tucapel",
    "Yumbel"
  ],
  "Araucanía": [
    "Angol",
    "Carahue",
    "Cholchol",
    "Collipulli",
    "Cunco",
    "Curacautín",
    "Curarrehue",
    "Ercilla",
    "Freire",
    "Galvarino",
    "Gorbea",
    "Lautaro",
    "Loncoche",
    "Lonquimay",
    "Los Sauces",
    "Lumaco",
    "Melipeuco",
    "Nueva Imperial",
    "Padre las Casas",
    "Perquenco",
    "Pitrufquén",
    "Pucón",
    "Purén",
    "Renaico",
    "Saavedra",
    "Temuco",
    "Teodoro Schmidt",
    "Toltén",
    "Traiguén",
    "Victoria",
    "Vilcún",
    "Villarrica"
  ],
  "Los Ríos": [
    "Corral",
    "Futrono",
    "La Unión",
    "Lago Ranco",
    "Lanco",
    "Los Lagos",
    "Mariquina",
    "Máfil",
    "Paillaco",
    "Panguipulli",
    "Río Bueno",
    "Valdivia"
  ],
  "Los Lagos": [
    "Ancud",
    "Calbuco",
    "Castro",
    "Chaitén",
    "Chonchi",
    "Cochamó",
    "Curaco de Vélez",
    "Dalcahue",
    "Fresia",
    "Frutillar",
    "Futaleufú",
    "Hualaihué",
    "Llanquihue",
    "Los Muermos",
    "Maullín",
    "Osorno",
    "Palena",
    "Puerto Montt",
    "Puerto Octay",
    "Puerto Varas",
    "Puqueldón",
    "Purranque",
    "Puyehue",
    "Queilén",
    "Quellón",
    "Quemchi",
    "Quinchao",
    "Río Negro",
    "San Juan de la Costa",
    "San Pablo"
  ],
  "Aisén": [
    "Aisén",
    "Chile Chico",
    "Cisnes",
    "Cochrane",
    "Coihaique",
    "Guaitecas",
    "Lago Verde",
    "O’Higgins",
    "Río Ibáñez",
    "Tortel"
  ],
  "Magallanes y de la Antártica Chilena": [
    "Antártica",
    "Cabo de Hornos (Ex Navarino)",
    "Laguna Blanca",
    "Natales",
    "Porvenir",
    "Primavera",
    "Punta Arenas",
    "Río Verde",
    "San Gregorio",
    "Timaukel",
    "Torres del Paine"
  ]
};

List<Map> comunasOriginal = [
  {
    "region": "Arica y Parinacota",
    "numero": "XV",
    "comunas": ["Arica", "Camarones", "General Lagos", "Putre"]
  },
  {
    "region": "Tarapacá",
    "numero": "I",
    "comunas": [
      "Alto Hospicio",
      "Camiña",
      "Colchane",
      "Huara",
      "Iquique",
      "Pica",
      "Pozo Almonte"
    ]
  },
  {
    "region": "Antofagasta",
    "numero": "II",
    "comunas": [
      "Antofagasta",
      "Calama",
      "María Elena",
      "Mejillones",
      "Ollagüe",
      "San Pedro de Atacama",
      "Sierra Gorda",
      "Taltal",
      "Tocopilla"
    ]
  },
  {
    "region": "Atacama",
    "numero": "III",
    "comunas": [
      "Alto del Carmen",
      "Caldera",
      "Chañaral",
      "Copiapó",
      "Diego de Almagro",
      "Freirina",
      "Huasco",
      "Tierra Amarilla",
      "Vallenar"
    ]
  },
  {
    "region": "Coquimbo",
    "numero": "IV",
    "comunas": [
      "Andacollo",
      "Canela",
      "Combarbalá",
      "Coquimbo",
      "Illapel",
      "La Higuera",
      "La Serena",
      "Los Vilos",
      "Monte Patria",
      "Ovalle",
      "Paiguano",
      "Punitaqui",
      "Río Hurtado",
      "Salamanca",
      "Vicuña"
    ]
  },
  {
    "region": "Valparaíso",
    "numero": "V",
    "comunas": [
      "Algarrobo",
      "Cabildo",
      "Calera",
      "Calle Larga",
      "Cartagena",
      "Casablanca",
      "Catemu",
      "Concón",
      "El Quisco",
      "El Tabo",
      "Hijuelas",
      "Isla de Pascua",
      "Juan Fernández",
      "La Cruz",
      "La Ligua",
      "Limache",
      "Llaillay",
      "Los Andes",
      "Nogales",
      "Olmué",
      "Panquehue",
      "Papudo",
      "Petorca",
      "Puchuncaví",
      "Putaendo",
      "Quillota",
      "Quilpué",
      "Quintero",
      "Rinconada",
      "San Antonio",
      "San Esteban",
      "San Felipe",
      "Santa María",
      "Santo Domingo",
      "Valparaíso",
      "Villa Alemana",
      "Viña del Mar",
      "Zapallar"
    ]
  },
  {
    "region": "Metropolitana de Santiago",
    "numero": "MET",
    "comunas": [
      "Alhué",
      "Buin",
      "Calera de Tango",
      "Cerrillos",
      "Cerro Navia",
      "Colina",
      "Conchalí",
      "Curacaví",
      "El Bosque",
      "El Monte",
      "Estación Central",
      "Huechuraba",
      "Independencia",
      "Isla de Maipo",
      "La Cisterna",
      "La Florida",
      "La Granja",
      "La Pintana",
      "La Reina",
      "Lampa",
      "Las Condes",
      "Lo Barnechea",
      "Lo Espejo",
      "Lo Prado",
      "Macul",
      "Maipú",
      "María Pinto",
      "Melipilla",
      "Ñuñoa",
      "Padre Hurtado",
      "Paine",
      "Pedro Aguirre Cerda",
      "Peñaflor",
      "Peñalolén",
      "Pirque",
      "Providencia",
      "Pudahuel",
      "Puente Alto",
      "Quilicura",
      "Quinta Normal",
      "Recoleta",
      "Renca",
      "San Bernardo",
      "San Joaquín",
      "San José de Maipo",
      "San Miguel",
      "San Pedro",
      "San Ramón",
      "Santiago",
      "Talagante",
      "Tiltil",
      "Vitacura"
    ]
  },
  {
    "region": "Libertador Gral. Bernardo O’Higgins",
    "numero": "VI",
    "comunas": [
      "Chimbarongo",
      "Chépica",
      "Codegua",
      "Coinco",
      "Coltauco",
      "Doñihue",
      "Graneros",
      "La Estrella",
      "Las Cabras",
      "Litueche",
      "Lolol",
      "Machalí",
      "Malloa",
      "Marchihue",
      "Nancagua",
      "Navidad",
      "Olivar",
      "Palmilla",
      "Paredones",
      "Peralillo",
      "Peumo",
      "Pichidegua",
      "Pichilemu",
      "Placilla",
      "Pumanque",
      "Quinta de Tilcoco",
      "Rancagua",
      "Rengo",
      "Requínoa",
      "San Fernando",
      "San Francisco de Mostazal",
      "San Vicente de Tagua Tagua",
      "Santa Cruz"
    ]
  },
  {
    "region": "Maule",
    "numero": "VII",
    "comunas": [
      "Cauquenes",
      "Chanco",
      "Colbún",
      "Constitución",
      "Curepto",
      "Curicó",
      "Empedrado",
      "Hualañé",
      "Licantén",
      "Linares",
      "Longaví",
      "Maule",
      "Molina",
      "Parral",
      "Pelarco",
      "Pelluhue",
      "Pencahue",
      "Rauco",
      "Retiro",
      "Romeral",
      "Río Claro",
      "Sagrada Familia",
      "San Clemente",
      "San Javier de Loncomilla",
      "San Rafael",
      "Talca",
      "Teno",
      "Vichuquén",
      "Villa Alegre",
      "Yerbas Buenas"
    ]
  },
  {
    "region": "Ñuble",
    "numero": "XVI",
    "comunas": [
      "Bulnes",
      "Chillán Viejo",
      "Chillán",
      "Cobquecura",
      "Coelemu",
      "Coihueco",
      "El Carmen",
      "Ninhue",
      "Ñiquén",
      "Pemuco",
      "Pinto",
      "Portezuelo",
      "Quillón",
      "Quirihue",
      "Ránquil",
      "San Carlos",
      "San Fabián",
      "San Ignacio",
      "San Nicolás",
      "Treguaco",
      "Yungay"
    ]
  },
  {
    "region": "Biobío",
    "numero": "VIII",
    "comunas": [
      "Alto Biobío",
      "Antuco",
      "Arauco",
      "Cabrero",
      "Cañete",
      "Chiguayante",
      "Concepción",
      "Contulmo",
      "Coronel",
      "Curanilahue",
      "Florida",
      "Hualpén",
      "Hualqui",
      "Laja",
      "Lebu",
      "Los Álamos",
      "Los Ángeles",
      "Lota",
      "Mulchén",
      "Nacimiento",
      "Negrete",
      "Penco",
      "Quilaco",
      "Quilleco",
      "San Pedro de la Paz",
      "San Rosendo",
      "Santa Bárbara",
      "Santa Juana",
      "Talcahuano",
      "Tirúa",
      "Tomé",
      "Tucapel",
      "Yumbel"
    ]
  },
  {
    "region": "Araucanía",
    "numero": "IX",
    "comunas": [
      "Angol",
      "Carahue",
      "Cholchol",
      "Collipulli",
      "Cunco",
      "Curacautín",
      "Curarrehue",
      "Ercilla",
      "Freire",
      "Galvarino",
      "Gorbea",
      "Lautaro",
      "Loncoche",
      "Lonquimay",
      "Los Sauces",
      "Lumaco",
      "Melipeuco",
      "Nueva Imperial",
      "Padre las Casas",
      "Perquenco",
      "Pitrufquén",
      "Pucón",
      "Purén",
      "Renaico",
      "Saavedra",
      "Temuco",
      "Teodoro Schmidt",
      "Toltén",
      "Traiguén",
      "Victoria",
      "Vilcún",
      "Villarrica"
    ]
  },
  {
    "region": "Los Ríos",
    "numero": "XIV",
    "comunas": [
      "Corral",
      "Futrono",
      "La Unión",
      "Lago Ranco",
      "Lanco",
      "Los Lagos",
      "Mariquina",
      "Máfil",
      "Paillaco",
      "Panguipulli",
      "Río Bueno",
      "Valdivia"
    ]
  },
  {
    "region": "Los Lagos",
    "numero": "X",
    "comunas": [
      "Ancud",
      "Calbuco",
      "Castro",
      "Chaitén",
      "Chonchi",
      "Cochamó",
      "Curaco de Vélez",
      "Dalcahue",
      "Fresia",
      "Frutillar",
      "Futaleufú",
      "Hualaihué",
      "Llanquihue",
      "Los Muermos",
      "Maullín",
      "Osorno",
      "Palena",
      "Puerto Montt",
      "Puerto Octay",
      "Puerto Varas",
      "Puqueldón",
      "Purranque",
      "Puyehue",
      "Queilén",
      "Quellón",
      "Quemchi",
      "Quinchao",
      "Río Negro",
      "San Juan de la Costa",
      "San Pablo"
    ]
  },
  {
    "region": "Aisén",
    "numero": "XI",
    "comunas": [
      "Aisén",
      "Chile Chico",
      "Cisnes",
      "Cochrane",
      "Coihaique",
      "Guaitecas",
      "Lago Verde",
      "O’Higgins",
      "Río Ibáñez",
      "Tortel"
    ]
  },
  {
    "region": "Magallanes y de la Antártica Chilena",
    "numero": "XII",
    "comunas": [
      "Antártica",
      "Cabo de Hornos (Ex Navarino)",
      "Laguna Blanca",
      "Natales",
      "Porvenir",
      "Primavera",
      "Punta Arenas",
      "Río Verde",
      "San Gregorio",
      "Timaukel",
      "Torres del Paine"
    ]
  }
];

List<Map> properties = [
  {
    "title": "Parcela con cerros",
    "address": "Temuco",
    "description":
        "PARCELAS DE AGRADO ALTO EL ROSARIO Hermosas Parcelas desde 5000 mt2, con medidor de agua potable y luz (soterrada) instalados dentro de la parcela, ubicadas en Padre Hurtado. Alto El Rosario es un proyecto inmobiliario consolidado, pensado en aquellos que buscan tranquilidad y una excelente conectividad, actualmente estamos liquidando las últimas unidades disponibles de nuestra primera etapa, tenemos unidades principalmente planas a 3.000UF. En su segunda etapa contara con 157 parcelas, las cuales tienen un valor de 3.200UF. Un excelente proyecto de inversión ubicado en una zona exclusiva de alto desarrollo, sustentable y creciente plusvalía.",
    "contact": "+56 9 8888 8888",
    "surface": "5000 m2",
    "services": "luz, agua, gas",
    "price": "UF 9000",
    "image":
        "http://imgclasificados4.emol.com/Proyectos/imagenes/docs_corredores/archivos/610/936637/422712bc0643a3ea0aa7fc49cf284a74.jpg"
  },
  {
    "title": "Parcela en la montaña",
    "address": "Villarica",
    "description": "lorem ipsum",
    "contact": "+5692749274",
    "surface": "2300 m2",
    "price": "UF 500",
    "image":
        "http://imgclasificados4.emol.com/Proyectos/imagenes/docs_corredores/archivos/610/936637/422712bc0643a3ea0aa7fc49cf284a74.jpg"
  },
  {
    "title": "Parcela con vista al mar",
    "address": "Concepcion",
    "description": "lorem ipsum",
    "contact": "+56 9 8888 8888",
    "surface": "3500 m2",
    "services": "luz, agua, gas",
    "price": "UF 1000",
    "image":
        "http://imgclasificados4.emol.com/Proyectos/imagenes/docs_corredores/archivos/610/936637/422712bc0643a3ea0aa7fc49cf284a74.jpg"
  },
];
// superficie, contacto, dirección, precio, factibilidad servicios y una galería

List<Map> propertiesChats = [
  {
    "propertyName": "Parcela 10 los aromos",
    "ownerName": "John Doe",
    "imageURL": "https://i.imgur.com/ALHwjKY.jpg",
    "lastTime": "Now"
  },
  {
    "propertyName": "Campo Exterior Casa 2",
    "ownerName": "Stan Smith",
    "imageURL": "https://i.imgur.com/k5Qo1F3.jpg",
    "lastTime": "Yesterday"
  },
  {
    "propertyName": "Sitio San Juan km 46",
    "ownerName": "George Lucas",
    "imageURL": "https://i.imgur.com/eRM6hHb.jpg",
    "lastTime": "31 Mar"
  },
  {
    "propertyName": "José Hidalgo 223 casa C",
    "ownerName": "Kevin Parker",
    "imageURL": "https://i.imgur.com/cB9xxIg.jpeg",
    "lastTime": "28 Mar"
  },
  {
    "propertyName": "Las peras 3351",
    "ownerName": "Gastón Gaudio",
    "imageURL": "https://i.imgur.com/t95JyAn.jpg",
    "lastTime": "23 Mar"
  },
  {
    "propertyName": "Manuel Ossandón 13",
    "ownerName": "Marcelo Ríos",
    "imageURL": "https://i.imgur.com/sqRgJ4d.jpg",
    "lastTime": "17 Mar"
  },
  {
    "propertyName": "Eliodoro Yañez 772",
    "ownerName": "Marco Tulio Cicerón",
    "imageURL": "https://i.imgur.com/hZvLNya.jpg",
    "lastTime": "24 Feb"
  },
  {
    "propertyName": "Calle Larga 334 parcela 3",
    "ownerName": "Casio Longinos",
    "imageURL": "https://i.imgur.com/aMdsdiK.jpg",
    "lastTime": "18 Feb"
  },
];

List<Map> chatMessages = [
  {
    "messageContent": "Hello, Will",
    "messageType": "sender",
    "author": "Cristobal Jones",
    "timeStamp": "23/05/2021"
  },
  {
    "messageContent": "How have you been?",
    "messageType": "sender",
    "author": "Roberto Vidal",
    "timeStamp": "23/05/2021"
  },
  {
    "messageContent": "Hey Kriss, I am doing fine dude. wbu?",
    "messageType": "receiver",
    "author": "Pablo Garnham",
    "timeStamp": "23/05/2021"
  },
  {
    "messageContent": "ehhhh, doing OK.",
    "messageType": "sender",
    "author": "Roberto Vidal",
    "timeStamp": "23/05/2021"
  },
  {
    "messageContent": "Is there any thing wrong?",
    "messageType": "receiver",
    "author": "Pablo Garnham",
    "timeStamp": "23/05/2021"
  },
];
